[package]
name = "gbhwdb-backend"
version = "0.0.0"
authors = ["Joonas Javanainen <joonas.javanainen@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
anyhow = "1.0"
lazy_static = "1.3"
regex = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
