[package]
name = "gbhwdb-backend"
version = "0.0.0"
authors = ["Joonas Javanainen <joonas.javanainen@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.57"
log = "0.4.17"
once_cell = "1.12.0"
regex = "1.5.6"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
time = { version = "0.3.9", features = ["serde", "parsing", "formatting", "macros"] }
