[package]
name = "gbhwdb-deploy"
version = "0.0.0"
authors = ["Joonas Javanainen <joonas.javanainen@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
anyhow = "1.0"
base64 = "0.13"
chrono = "0.4"
log = "0.4"
md-5 = "0.9"
rayon = "1.4"
rusoto_core = "0.46"
rusoto_s3 = "0.46"
simplelog = "0.10"
tokio = { version = "1.6.0", features = ["fs", "macros", "rt-multi-thread"] }
walkdir = "2.2"
xdg-mime = "0.3"
